FIRST_PATH = "./docs/languages.md"
SECOND_PATH = "./docs/en-GB/README.md"
COMBINED_PATH = "README.md"

final = "[//]: <> (Do not edit this file. This is generated by build_readme.py. Instead, edit the README in docs.)\n"

print("Reading from:", FIRST_PATH)
with open(FIRST_PATH, "r") as f:
    final += f.read() + "\n\n"

print("Reading from:", SECOND_PATH)
with open(SECOND_PATH, "r") as f:
    final += f.read()

print("Writing to:", COMBINED_PATH)
with open(COMBINED_PATH, "w") as f:
    f.write(final)